fix: header not showing on mobile device
makeplane/plane pull request #1348
Opened 2023-06-21 05:34 UTC by ChandanJal

fix: problem with header that was not showing on the mobile device in dashboard

2023-06-21 09:16 UTC, TheDevMinerTV requested changes

2023-06-21 09:19 UTC, ChandanJal commented on apps/app/hooks/use-window-width.tsx
> +  function handleWidthChange(w?: UIEvent) {
@TheDevMinerTV  Yes absolutely

2023-06-24 10:15 UTC, aaryan610 commented
Hi @ChandanJal, thanks for your contribution to fixing this bug, however, the approach used by you would be an overkill for such a small bug.

2023-06-24 10:16 UTC, aaryan610 commented
Hi @ChandanJal, thanks for your contribution to fixing this bug, however, the approach used by you would be overkill for such a small bug.

We have fixed this bug and it'll be live once the PR #1389 is merged.

2023-06-24 10:16 UTC, closed without merging