fix: csv issue export
makeplane/plane pull request #1794
Opened 2023-08-07 08:59 UTC by NarayanBavisetti

fix: csv issue export

2023-08-07 09:57 UTC, sriramveeraghanta requested changes

2023-08-07 09:57 UTC, sriramveeraghanta commented on apiserver/plane/bgtasks/export_task.py
> +            print(assignees_names,"assignees_names")
Remove these print statements

2023-08-10 10:04 UTC, NarayanBavisetti commented on apiserver/plane/bgtasks/export_task.py
> +            print(assignees_names,"assignees_names")
Done

2023-08-11 11:48 UTC, pablohashescobar requested changes

2023-08-11 11:48 UTC, pablohashescobar commented on apiserver/plane/api/views/exporter.py
> +            print(e)
Please put `capture_exception` here

2023-08-11 11:48 UTC, pablohashescobar commented on apiserver/plane/api/views/exporter.py
> +            ).select_related("workspace")
also do a select related to `initiated_by` since we are getting the initiated_by detail

2023-08-11 11:48 UTC, pablohashescobar commented on apiserver/plane/api/views/exporter.py
> +            history = ExporterHistory.objects.filter(
change the name of the variable to `exporter_history`

2023-08-11 11:48 UTC, pablohashescobar commented on apiserver/plane/bgtasks/export_task.py
> +# def format_datetime(dt):
Remove this commented code if not required

2023-08-11 14:39 UTC, pablohashescobar approved these changes

2023-08-11 14:39 UTC, merged