[chore] Added Husky for Automating Building and Linting Projects Before Push
makeplane/plane pull request #2032
Opened 2023-08-31 09:30 UTC by henit-chobisa

## Tasks
- [x] Added Husky as a dependency in workspace root
- [x] Added Pre-Push Script for Conditionally Building Projects according to changes Introduced.

Before Every Push, in any Branch, husky will run a pre-push script which includes linting and building of the modified project directories, ensuring that no code in any branch of the repository breaks while building. ✌🏼

2023-08-31 10:50 UTC, Palanikannan1437 commented
> ## Tasks
> - [x] Added Husky as a dependency in workspace root
> - [x] Added Pre-Push Script for Conditionally Building Projects according to changes Introduced.
> 
> Before Every Push, in any Branch, husky will run a pre-push script which includes linting and building of the modified project directories, ensuring that no code in any branch of the repository breaks while building. ✌🏼

THANK YOU for this @henit-chobisa , sometimes you just forget to build before pushing to just see the CI fail, this is gonna improve the loop so much!!

2023-09-01 17:52 UTC, sriramveeraghanta requested changes

2023-09-01 17:52 UTC, sriramveeraghanta commented on package.json
> +    "husky": "^8.0.3"
Husky can be a dev dependency right?

2023-09-02 08:17 UTC, sriramveeraghanta approved these changes

2023-09-02 08:17 UTC, merged