chore: added pre-release tag for workflow publications
makeplane/plane pull request #2133
Opened 2023-09-09 12:13 UTC by henit-chobisa

## Tasks
- [x] Added `pre-release` tag for running release workflow on `releases` as well as `pre-releases`

2023-09-09 12:54 UTC, pablohashescobar requested changes

2023-09-09 15:28 UTC, henit-chobisa commented on docker-compose-hub.yml
> +                ports:
Removed it ✅

2023-09-09 16:54 UTC, pablohashescobar approved these changes

2023-09-09 16:56 UTC, pablohashescobar commented
@henit-chobisa just to confirm we will be removing the worker images from now on right ?

2023-09-09 17:09 UTC, henit-chobisa commented
> @henit-chobisa just to confirm we will be removing the worker images from now on right ? Everything will be using backend container only ?

Yes @pablohashescobar Nikhil, the backend container is capable for worker and beat as well, just the change of command. Hence, we can use the same backend image for the worker purposes as well.

2023-09-09 17:10 UTC, pablohashescobar commented
Awesome. Let's update the docs as well.

2023-09-09 17:16 UTC, henit-chobisa commented
@pablohashescobar 
Sure Nikhil, also just to clarify, the compose hub won't work until a user exposes the backend port, I have to make the change to localhost thing.

2023-09-09 17:16 UTC, pablohashescobar commented
Yep let's make it localhost.

2023-09-11 12:32 UTC, sriramveeraghanta approved these changes

2023-09-11 12:32 UTC, merged