fix: mention notification
makeplane/plane pull request #2670
Opened 2023-11-06 13:18 UTC by NarayanBavisetti

fix:

-  users mentioned in this description will now receive notifications.

2023-11-08 06:07 UTC, pablohashescobar requested changes

2023-11-08 06:48 UTC, NarayanBavisetti commented on apiserver/plane/bgtasks/notification_task.py
> +                workspace=project.workspace
ok

2023-11-08 06:48 UTC, NarayanBavisetti commented on apiserver/plane/bgtasks/notification_task.py
> +                mention=mentioned_user,
Yes, we can do that

2023-11-09 12:50 UTC, sriramveeraghanta approved these changes

2023-11-09 12:52 UTC, pablohashescobar approved these changes

2023-11-09 12:52 UTC, merged