[WEB-1255] chore: Refactor existing Space app for project publish
makeplane/plane pull request #5107
Opened 2024-07-11 15:06 UTC by rahulramesha

This PR includes Refactoring in Existing Project publish by introducing Pagination. And also include changes to make way for Advanced views in Space App.

https://github.com/makeplane/plane/assets/71900764/dded0e69-738c-4964-abac-2a69273a7792

2024-07-12 12:57 UTC, SatishGandham commented on space/core/components/issues/issue-layouts/list/header.tsx
> +        <StateGroupIcon stateGroup={state?.group ?? "backlog"} color={state?.color} height="14" width="14" />
Can a state exist without group?

2024-07-12 13:20 UTC, SatishGandham commented on space/core/components/issues/peek-overview/issue-emoji-reactions.tsx
> +          if (reactions?.length > 0)
Its always an array.

2024-07-12 13:31 UTC, SatishGandham commented on space/core/components/issues/peek-overview/issue-vote-reactions.tsx
> +            {allUpVotes?.length > 0 ? (
Isn't this always an array, and on line 79 to.

2024-07-12 13:56 UTC, SatishGandham requested changes

2024-07-12 13:56 UTC, SatishGandham commented on space/core/components/issues/peek-overview/issue-properties.tsx
> +            <StateGroupIcon stateGroup={state?.group ?? "backlog"} color={state?.color} />
Shouldnt color also have a fallback?

2024-07-12 14:21 UTC, SatishGandham approved these changes

2024-07-15 07:55 UTC, pablohashescobar approved these changes

2024-07-15 13:05 UTC, merged