refactor: page actions menu
makeplane/plane pull request #6076
Opened 2024-11-20 07:37 UTC by aaryan610

2024-11-20 10:34 UTC, NarayanBavisetti approved these changes

2024-11-20 10:49 UTC, SatishGandham commented on packages/ui/src/dropdowns/custom-menu.tsx
> +    if (isOpen) onMenuClose?.();
Wouldn't it be cleaner if its written as
`if(isOpen && onMenuClose)`

2024-11-20 10:56 UTC, SatishGandham requested changes

2024-11-20 10:56 UTC, SatishGandham commented on web/core/components/pages/dropdowns/actions.tsx
> +  const arrangedOptions = optionsOrder
this should be memoized.

2024-11-20 11:38 UTC, rahulramesha commented on web/core/components/pages/dropdowns/actions.tsx
> +        shouldRender: canCurrentUserChangeAccess,
@aaryan610 check this out. Also try to use enums for keys instead of string values

2024-11-21 09:16 UTC, rahulramesha approved these changes

2024-12-19 14:50 UTC, closed without merging